name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: sudo apt install python3 gcc binutils make wget tar
    - name: setup toolchain
      run: chmod +x toolchain.sh && ./toolchain.sh
    - name: make
      run: make
