name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: sudo apt install python3 gcc binutils make wget tar
    - name: setup toolchain
      run: cd /usr && mkdir build-gcc & mkdir build-bin && wget https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.xz -O binutils.tar.xz & wget https://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.xz -O gcc.tar.xz && tar -xf binutils.tar.xz & tar -xf gcc.tar.xz
    - name: make
      run: make
